import type { Product, ProductFilters, ProductProvider } from "@/types";

export function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function localProduct(p: Omit<Product, "createdAt" | "updatedAt">): Product {
  const now = new Date().toISOString();
  return { ...p, createdAt: now, updatedAt: now };
}

export const MOCK_PRODUCTS: Product[] = [
  // User-supplied catalog images (files in public/products/).
  localProduct({
    id: "wbc-tee-black-crew",
    externalId: "wbc-tee-black-crew",
    provider: "mock",
    brand: "Mono & Co",
    name: "Black Essential Crew Tee",
    slug: "black-essential-crew-tee-wbc-tee-black-crew",
    description: "Classic black crew-neck t-shirt in soft breathable cotton. A wardrobe essential.",
    category: "T-Shirts",
    gender: "unisex",
    price: 899,
    currency: "INR",
    originalPrice: 1199,
    discount: 25,
    colors: ["black"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/black-crew-tee.jpg"],
    thumbnail: "/products/black-crew-tee.jpg",
    productUrl: "https://example-retailer.com/p/wbc-tee-black-crew",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-black-crew?aff=wbc",
    availability: true,
    rating: 4.6,
    popularity: 100,
    tags: ["tshirt", "black", "crew", "basic", "casual", "everyday", "cotton"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-tee-white-polo",
    externalId: "wbc-tee-white-polo",
    provider: "mock",
    brand: "Nordelle",
    name: "White Classic Polo T-Shirt",
    slug: "white-classic-polo-t-shirt-wbc-tee-white-polo",
    description: "Smart white polo t-shirt with ribbed collar and button placket. Perfect for college and casual outings.",
    category: "T-Shirts",
    gender: "unisex",
    price: 1299,
    currency: "INR",
    originalPrice: 1699,
    discount: 24,
    colors: ["white"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-polo-tee.jpg"],
    thumbnail: "/products/white-polo-tee.jpg",
    productUrl: "https://example-retailer.com/p/wbc-tee-white-polo",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-white-polo?aff=wbc",
    availability: true,
    rating: 4.7,
    popularity: 100,
    tags: ["tshirt", "polo", "white", "collar", "casual", "college", "smart"],
    style: ["casual", "smart-casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-tee-light-blue-crew",
    externalId: "wbc-tee-light-blue-crew",
    provider: "mock",
    brand: "Mono & Co",
    name: "Light Blue Essential Crew Tee",
    slug: "light-blue-essential-crew-tee-wbc-tee-light-blue-crew",
    description: "Light blue crew-neck t-shirt in soft breathable cotton. A fresh everyday essential.",
    category: "T-Shirts",
    gender: "unisex",
    price: 899,
    currency: "INR",
    originalPrice: 1199,
    discount: 25,
    colors: ["lightblue", "blue"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/light-blue-crew-tee.jpg"],
    thumbnail: "/products/light-blue-crew-tee.jpg",
    productUrl: "https://example-retailer.com/p/wbc-tee-light-blue-crew",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-light-blue-crew?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 96,
    tags: ["tshirt", "blue", "crew", "basic", "casual", "everyday", "cotton"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-tee-beige-crew",
    externalId: "wbc-tee-beige-crew",
    provider: "mock",
    brand: "Mono & Co",
    name: "Beige Essential Crew Tee",
    slug: "beige-essential-crew-tee-wbc-tee-beige-crew",
    description: "Beige crew-neck t-shirt in soft breathable cotton. Neutral tone for easy pairing.",
    category: "T-Shirts",
    gender: "unisex",
    price: 899,
    currency: "INR",
    originalPrice: 1199,
    discount: 25,
    colors: ["beige"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/beige-crew-tee.jpg"],
    thumbnail: "/products/beige-crew-tee.jpg",
    productUrl: "https://example-retailer.com/p/wbc-tee-beige-crew",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-beige-crew?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 95,
    tags: ["tshirt", "beige", "crew", "basic", "casual", "everyday", "cotton"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-tee-chocolate-brown-crew",
    externalId: "wbc-tee-chocolate-brown-crew",
    provider: "mock",
    brand: "Mono & Co",
    name: "Chocolate Brown Essential Crew Tee",
    slug: "chocolate-brown-essential-crew-tee-wbc-tee-chocolate-brown-crew",
    description: "Chocolate brown crew-neck t-shirt in soft breathable cotton. Rich earthy tone.",
    category: "T-Shirts",
    gender: "unisex",
    price: 899,
    currency: "INR",
    originalPrice: 1199,
    discount: 25,
    colors: ["brown"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/chocolate-brown-crew-tee.jpg"],
    thumbnail: "/products/chocolate-brown-crew-tee.jpg",
    productUrl: "https://example-retailer.com/p/wbc-tee-chocolate-brown-crew",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-chocolate-brown-crew?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 94,
    tags: ["tshirt", "brown", "crew", "basic", "casual", "everyday", "cotton"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-hoodie-white-pullover",
    externalId: "wbc-hoodie-white-pullover",
    provider: "mock",
    brand: "Mono & Co",
    name: "White Classic Pullover Hoodie",
    slug: "white-classic-pullover-hoodie-wbc-hoodie-white-pullover",
    description: "Classic white pullover hoodie with drawstrings and kangaroo pocket. Soft fleece for winter.",
    category: "Hoodies",
    gender: "unisex",
    price: 1799,
    currency: "INR",
    originalPrice: 2299,
    discount: 22,
    colors: ["white"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-pullover-hoodie.jpg"],
    thumbnail: "/products/white-pullover-hoodie.jpg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-white-pullover",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-white-pullover?aff=wbc",
    availability: true,
    rating: 4.6,
    popularity: 93,
    tags: ["hoodie", "white", "winter", "casual", "fleece", "pullover"],
    style: ["casual", "streetwear"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-tan-pullover",
    externalId: "wbc-hoodie-tan-pullover",
    provider: "mock",
    brand: "Mono & Co",
    name: "Tan Classic Pullover Hoodie",
    slug: "tan-classic-pullover-hoodie-wbc-hoodie-tan-pullover",
    description: "Tan pullover hoodie with drawstrings and kangaroo pocket. Warm fleece everyday layer.",
    category: "Hoodies",
    gender: "unisex",
    price: 1799,
    currency: "INR",
    originalPrice: 2299,
    discount: 22,
    colors: ["beige", "brown"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/tan-pullover-hoodie.jpg"],
    thumbnail: "/products/tan-pullover-hoodie.jpg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-tan-pullover",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-tan-pullover?aff=wbc",
    availability: true,
    rating: 4.6,
    popularity: 92,
    tags: ["hoodie", "tan", "winter", "casual", "fleece", "pullover"],
    style: ["casual", "streetwear"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-shirt-green-black-flannel",
    externalId: "wbc-shirt-green-black-flannel",
    provider: "mock",
    brand: "Urban Thread",
    name: "Green Black Check Flannel Shirt",
    slug: "green-black-check-flannel-shirt-wbc-shirt-green-black-flannel",
    description: "Green and black check flannel shirt with chest pockets. Layer it over a white tee.",
    category: "Shirts",
    gender: "men",
    price: 1599,
    currency: "INR",
    originalPrice: 2099,
    discount: 24,
    colors: ["green", "black"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/green-black-check-flannel-shirt.jpg"],
    thumbnail: "/products/green-black-check-flannel-shirt.jpg",
    productUrl: "https://example-retailer.com/p/wbc-shirt-green-black-flannel",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-shirt-green-black-flannel?aff=wbc",
    availability: true,
    rating: 4.4,
    popularity: 89,
    tags: ["shirt", "flannel", "check", "green", "casual", "layering"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-shirt-sage-green-plaid",
    externalId: "wbc-shirt-sage-green-plaid",
    provider: "mock",
    brand: "Urban Thread",
    name: "Sage Green White Plaid Casual Shirt",
    slug: "sage-green-white-plaid-casual-shirt-wbc-shirt-sage-green-plaid",
    description: "Sage green and white plaid casual shirt. Lightweight everyday button-up.",
    category: "Shirts",
    gender: "men",
    price: 1499,
    currency: "INR",
    originalPrice: 1999,
    discount: 25,
    colors: ["green", "white"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/sage-green-white-plaid-shirt.jpg"],
    thumbnail: "/products/sage-green-white-plaid-shirt.jpg",
    productUrl: "https://example-retailer.com/p/wbc-shirt-sage-green-plaid",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-shirt-sage-green-plaid?aff=wbc",
    availability: true,
    rating: 4.4,
    popularity: 88,
    tags: ["shirt", "plaid", "green", "casual", "button-up"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-shirt-teal-white-check",
    externalId: "wbc-shirt-teal-white-check",
    provider: "mock",
    brand: "Nordelle",
    name: "Teal Blue White Check Casual Shirt",
    slug: "teal-blue-white-check-casual-shirt-wbc-shirt-teal-white-check",
    description: "Teal blue shirt with white windowpane check. Smart-casual button-up.",
    category: "Shirts",
    gender: "men",
    price: 1699,
    currency: "INR",
    originalPrice: 2199,
    discount: 23,
    colors: ["blue", "teal", "white"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/teal-blue-white-check-shirt.jpg"],
    thumbnail: "/products/teal-blue-white-check-shirt.jpg",
    productUrl: "https://example-retailer.com/p/wbc-shirt-teal-white-check",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-shirt-teal-white-check?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 87,
    tags: ["shirt", "check", "teal", "blue", "casual", "smart-casual"],
    style: ["casual", "smart-casual"],
    occasion: ["college", "casual", "office"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-shirt-rust-orange-overshirt",
    externalId: "wbc-shirt-rust-orange-overshirt",
    provider: "mock",
    brand: "Urban Thread",
    name: "Rust Orange Solid Overshirt",
    slug: "rust-orange-solid-overshirt-wbc-shirt-rust-orange-overshirt",
    description: "Rust orange solid overshirt with flap pockets. Wear open over a white tee.",
    category: "Shirts",
    gender: "men",
    price: 1899,
    currency: "INR",
    originalPrice: 2499,
    discount: 24,
    colors: ["orange", "brown"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/rust-orange-solid-overshirt.jpg"],
    thumbnail: "/products/rust-orange-solid-overshirt.jpg",
    productUrl: "https://example-retailer.com/p/wbc-shirt-rust-orange-overshirt",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-shirt-rust-orange-overshirt?aff=wbc",
    availability: true,
    rating: 4.4,
    popularity: 86,
    tags: ["shirt", "overshirt", "orange", "solid", "casual", "layering"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-jacket-tan-denim-trucker",
    externalId: "wbc-jacket-tan-denim-trucker",
    provider: "mock",
    brand: "Northpeak",
    name: "Tan Brown Denim Trucker Jacket",
    slug: "tan-brown-denim-trucker-jacket-wbc-jacket-tan-denim-trucker",
    description: "Tan brown washed denim trucker jacket with flap pockets. Classic casual layer.",
    category: "Jackets",
    gender: "unisex",
    price: 2999,
    currency: "INR",
    originalPrice: 3799,
    discount: 21,
    colors: ["brown", "beige"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/tan-brown-denim-trucker-jacket.jpg"],
    thumbnail: "/products/tan-brown-denim-trucker-jacket.jpg",
    productUrl: "https://example-retailer.com/p/wbc-jacket-tan-denim-trucker",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-jacket-tan-denim-trucker?aff=wbc",
    availability: true,
    rating: 4.6,
    popularity: 91,
    tags: ["jacket", "denim", "trucker", "brown", "casual"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  // --- New jackets / hoodies / tees (named by look) ---
  localProduct({
    id: "wbc-hoodie-navy-grey-varsity",
    externalId: "wbc-hoodie-navy-grey-varsity",
    provider: "mock",
    brand: "Northpeak",
    name: "Navy Grey Varsity Raglan Hoodie",
    slug: "navy-grey-varsity-raglan-hoodie-wbc-hoodie-navy-grey-varsity",
    description: "Grey body with navy raglan sleeves, striped cuffs and hem. Sporty varsity-style pullover hoodie.",
    category: "Hoodies",
    gender: "men",
    price: 1899,
    currency: "INR",
    originalPrice: 2399,
    discount: 21,
    colors: ["grey", "navy", "blue", "white"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/navy-grey-varsity-raglan-hoodie.jpeg"],
    thumbnail: "/products/navy-grey-varsity-raglan-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-navy-grey-varsity",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-navy-grey-varsity?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 90,
    tags: ["hoodie", "varsity", "raglan", "navy", "grey", "stripe", "casual", "winter"],
    style: ["casual", "sporty"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-sky-blue-colorblock",
    externalId: "wbc-hoodie-sky-blue-colorblock",
    provider: "mock",
    brand: "Northpeak",
    name: "Sky Blue Grey Colorblock Hoodie",
    slug: "sky-blue-grey-colorblock-hoodie-wbc-hoodie-sky-blue-colorblock",
    description: "Sky blue, light grey and navy colorblock pullover hoodie with kangaroo pocket. Clean streetwear layer.",
    category: "Hoodies",
    gender: "unisex",
    price: 1799,
    currency: "INR",
    originalPrice: 2299,
    discount: 22,
    colors: ["blue", "grey", "navy"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/sky-blue-grey-colorblock-hoodie.jpeg"],
    thumbnail: "/products/sky-blue-grey-colorblock-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-sky-blue-colorblock",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-sky-blue-colorblock?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 89,
    tags: ["hoodie", "colorblock", "blue", "grey", "casual", "winter"],
    style: ["casual", "streetwear"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-white-green-stripe",
    externalId: "wbc-hoodie-white-green-stripe",
    provider: "mock",
    brand: "Northpeak",
    name: "White Forest Green Athletic Stripe Hoodie",
    slug: "white-forest-green-athletic-stripe-hoodie-wbc-hoodie-white-green-stripe",
    description: "White pullover hoodie with forest green hood and sleeve stripes plus contrast sporty arm bands.",
    category: "Hoodies",
    gender: "unisex",
    price: 1899,
    currency: "INR",
    originalPrice: 2399,
    discount: 21,
    colors: ["white", "green"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-forest-green-stripe-hoodie.jpeg"],
    thumbnail: "/products/white-forest-green-stripe-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-white-green-stripe",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-white-green-stripe?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 88,
    tags: ["hoodie", "white", "green", "stripe", "athletic", "casual", "winter"],
    style: ["casual", "sporty"],
    occasion: ["college", "casual", "sports"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-jacket-cream-tribal-trucker",
    externalId: "wbc-jacket-cream-tribal-trucker",
    provider: "mock",
    brand: "Urban Thread",
    name: "Cream Tribal Aztec Print Trucker Jacket",
    slug: "cream-tribal-aztec-print-trucker-jacket-wbc-jacket-cream-tribal-trucker",
    description: "Cream trucker jacket with colorful Aztec tribal print on yoke and sleeves. Statement button-up layer.",
    category: "Jackets",
    gender: "men",
    price: 3199,
    currency: "INR",
    originalPrice: 3999,
    discount: 20,
    colors: ["beige", "white", "multicolor"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/cream-tribal-trucker-jacket.jpeg"],
    thumbnail: "/products/cream-tribal-trucker-jacket.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-jacket-cream-tribal-trucker",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-jacket-cream-tribal-trucker?aff=wbc",
    availability: true,
    rating: 4.6,
    popularity: 87,
    tags: ["jacket", "trucker", "tribal", "aztec", "print", "cream", "boho"],
    style: ["casual", "boho"],
    occasion: ["college", "casual", "vacation"],
    season: ["winter", "all"],
  }),
  localProduct({
    id: "wbc-hoodie-mocha-tribal",
    externalId: "wbc-hoodie-mocha-tribal",
    provider: "mock",
    brand: "Northpeak",
    name: "Mocha Brown Tribal Geo Print Hoodie",
    slug: "mocha-brown-tribal-geo-print-hoodie-wbc-hoodie-mocha-tribal",
    description: "Mocha brown and beige hoodie with tribal geo band across chest and contrast pocket. Cozy fleece.",
    category: "Hoodies",
    gender: "unisex",
    price: 1999,
    currency: "INR",
    originalPrice: 2599,
    discount: 23,
    colors: ["brown", "beige"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/mocha-brown-tribal-hoodie.jpeg"],
    thumbnail: "/products/mocha-brown-tribal-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-mocha-tribal",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-mocha-tribal?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 86,
    tags: ["hoodie", "brown", "tribal", "geo", "print", "winter", "casual"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-white-orange-furry",
    externalId: "wbc-hoodie-white-orange-furry",
    provider: "mock",
    brand: "Mono & Co",
    name: "White Orange Sunset Ombre Furry Hoodie",
    slug: "white-orange-sunset-ombre-furry-hoodie-wbc-hoodie-white-orange-furry",
    description: "Super-soft fluffy white to sunset-orange ombre hoodie with wave design. Bold cozy streetwear.",
    category: "Hoodies",
    gender: "unisex",
    price: 2499,
    currency: "INR",
    originalPrice: 3199,
    discount: 22,
    colors: ["white", "orange"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-orange-sunset-furry-hoodie.jpeg"],
    thumbnail: "/products/white-orange-sunset-furry-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-white-orange-furry",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-white-orange-furry?aff=wbc",
    availability: true,
    rating: 4.7,
    popularity: 92,
    tags: ["hoodie", "furry", "ombre", "orange", "white", "plush", "streetwear"],
    style: ["streetwear", "casual"],
    occasion: ["casual", "party"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-black-tribal-pocket",
    externalId: "wbc-hoodie-black-tribal-pocket",
    provider: "mock",
    brand: "Northpeak",
    name: "Black Tribal Pocket Fleece Hoodie",
    slug: "black-tribal-pocket-fleece-hoodie-wbc-hoodie-black-tribal-pocket",
    description: "Black fleece hoodie with colorful tribal-print hood lining and chest pocket. Sherpa-lined hood.",
    category: "Hoodies",
    gender: "women",
    price: 1899,
    currency: "INR",
    originalPrice: 2499,
    discount: 24,
    colors: ["black", "multicolor"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/black-tribal-pocket-hoodie.jpeg"],
    thumbnail: "/products/black-tribal-pocket-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-black-tribal-pocket",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-black-tribal-pocket?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 85,
    tags: ["hoodie", "black", "tribal", "pocket", "fleece", "boho"],
    style: ["casual", "boho"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-beige-black-tribal",
    externalId: "wbc-hoodie-beige-black-tribal",
    provider: "mock",
    brand: "Northpeak",
    name: "Beige Black Tribal Side-Panel Hoodie",
    slug: "beige-black-tribal-side-panel-hoodie-wbc-hoodie-beige-black-tribal",
    description: "Beige and black hoodie with vibrant tribal side panel and small chest motif. Drop-shoulder fit.",
    category: "Hoodies",
    gender: "men",
    price: 1999,
    currency: "INR",
    originalPrice: 2599,
    discount: 23,
    colors: ["beige", "black", "multicolor"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/beige-black-tribal-panel-hoodie.jpeg"],
    thumbnail: "/products/beige-black-tribal-panel-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-beige-black-tribal",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-beige-black-tribal?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 84,
    tags: ["hoodie", "tribal", "beige", "black", "print", "streetwear"],
    style: ["streetwear", "casual"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-jacket-white-tribal-shacket",
    externalId: "wbc-jacket-white-tribal-shacket",
    provider: "mock",
    brand: "Urban Thread",
    name: "White Tribal Print Hooded Shacket Jacket",
    slug: "white-tribal-print-hooded-shacket-jacket-wbc-jacket-white-tribal-shacket",
    description: "White hooded shacket jacket with blue-red tribal print on sleeves, pockets and hem. Layer over hoodie.",
    category: "Jackets",
    gender: "men",
    price: 2999,
    currency: "INR",
    originalPrice: 3799,
    discount: 21,
    colors: ["white", "multicolor", "blue"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-tribal-hooded-shacket-jacket.jpeg"],
    thumbnail: "/products/white-tribal-hooded-shacket-jacket.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-jacket-white-tribal-shacket",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-jacket-white-tribal-shacket?aff=wbc",
    availability: true,
    rating: 4.6,
    popularity: 88,
    tags: ["jacket", "shacket", "tribal", "hooded", "white", "print"],
    style: ["casual", "streetwear"],
    occasion: ["college", "casual"],
    season: ["winter", "all"],
  }),
  localProduct({
    id: "wbc-tee-sage-wave-oversized",
    externalId: "wbc-tee-sage-wave-oversized",
    provider: "mock",
    brand: "Mono & Co",
    name: "Sage Green Off-White Wave Colorblock Oversized Tee",
    slug: "sage-green-off-white-wave-colorblock-oversized-tee-wbc-tee-sage-wave-oversized",
    description: "Minimalist oversized t-shirt with sage green wave colorblock on off-white. Small chest logo.",
    category: "T-Shirts",
    gender: "unisex",
    price: 999,
    currency: "INR",
    originalPrice: 1299,
    discount: 23,
    colors: ["green", "white", "beige"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/sage-green-wave-colorblock-oversized-tee.jpeg"],
    thumbnail: "/products/sage-green-wave-colorblock-oversized-tee.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-tee-sage-wave-oversized",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-sage-wave-oversized?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 90,
    tags: ["tshirt", "oversized", "colorblock", "sage", "green", "minimalist"],
    style: ["casual", "minimal"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-tee-white-abstract-art",
    externalId: "wbc-tee-white-abstract-art",
    provider: "mock",
    brand: "Mono & Co",
    name: "White Abstract Art Graphic Tee",
    slug: "white-abstract-art-graphic-tee-wbc-tee-white-abstract-art",
    description: "White crew tee with bold colorful abstract side graphic. Artsy everyday statement tee.",
    category: "T-Shirts",
    gender: "unisex",
    price: 899,
    currency: "INR",
    originalPrice: 1199,
    discount: 25,
    colors: ["white", "multicolor"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-abstract-art-graphic-tee.jpeg"],
    thumbnail: "/products/white-abstract-art-graphic-tee.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-tee-white-abstract-art",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-white-abstract-art?aff=wbc",
    availability: true,
    rating: 4.4,
    popularity: 87,
    tags: ["tshirt", "graphic", "abstract", "art", "white", "casual"],
    style: ["casual", "artsy"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-tee-white-sunset-city",
    externalId: "wbc-tee-white-sunset-city",
    provider: "mock",
    brand: "Mono & Co",
    name: "White Sunset City Splash Graphic Tee",
    slug: "white-sunset-city-splash-graphic-tee-wbc-tee-white-sunset-city",
    description: "White tee with sunset cityscape and paint-splash graphic. Urban artsy print.",
    category: "T-Shirts",
    gender: "unisex",
    price: 949,
    currency: "INR",
    originalPrice: 1249,
    discount: 24,
    colors: ["white", "multicolor", "yellow", "black"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-sunset-city-graphic-tee.jpeg"],
    thumbnail: "/products/white-sunset-city-graphic-tee.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-tee-white-sunset-city",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-white-sunset-city?aff=wbc",
    availability: true,
    rating: 4.4,
    popularity: 86,
    tags: ["tshirt", "graphic", "city", "sunset", "white", "casual"],
    style: ["casual", "streetwear"],
    occasion: ["college", "casual"],
    season: ["all"],
  }),
  localProduct({
    id: "wbc-hoodie-taupe-two-tone",
    externalId: "wbc-hoodie-taupe-two-tone",
    provider: "mock",
    brand: "Mono & Co",
    name: "Taupe Brown Two-Tone Panel Hoodie",
    slug: "taupe-brown-two-tone-panel-hoodie-wbc-hoodie-taupe-two-tone",
    description: "Taupe hoodie with dark brown side panels and kangaroo pocket. Minimal sporty pullover.",
    category: "Hoodies",
    gender: "unisex",
    price: 1799,
    currency: "INR",
    originalPrice: 2299,
    discount: 22,
    colors: ["brown", "beige"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/taupe-brown-two-tone-hoodie.jpg"],
    thumbnail: "/products/taupe-brown-two-tone-hoodie.jpg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-taupe-two-tone",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-taupe-two-tone?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 83,
    tags: ["hoodie", "taupe", "brown", "two-tone", "minimal", "casual"],
    style: ["casual", "minimal"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-cream-chevron",
    externalId: "wbc-hoodie-cream-chevron",
    provider: "mock",
    brand: "Northpeak",
    name: "Cream Coffee Brown Chevron Yoke Hoodie",
    slug: "cream-coffee-brown-chevron-yoke-hoodie-wbc-hoodie-cream-chevron",
    description: "Cream and coffee brown chevron yoke hoodie with contrast drawstrings. Warm everyday fleece.",
    category: "Hoodies",
    gender: "men",
    price: 1899,
    currency: "INR",
    originalPrice: 2399,
    discount: 21,
    colors: ["beige", "brown", "white"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/cream-coffee-chevron-yoke-hoodie.jpg"],
    thumbnail: "/products/cream-coffee-chevron-yoke-hoodie.jpg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-cream-chevron",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-cream-chevron?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 82,
    tags: ["hoodie", "cream", "brown", "chevron", "colorblock", "winter"],
    style: ["casual"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-white-smiley-colorblock",
    externalId: "wbc-hoodie-white-smiley-colorblock",
    provider: "mock",
    brand: "Nordelle",
    name: "White Tan Smiley Colorblock Hoodie",
    slug: "white-tan-smiley-colorblock-hoodie-wbc-hoodie-white-smiley-colorblock",
    description: "White, slate grey and tan triple colorblock hoodie with small smiley chest print. Playful streetwear.",
    category: "Hoodies",
    gender: "unisex",
    price: 1799,
    currency: "INR",
    originalPrice: 2299,
    discount: 22,
    colors: ["white", "beige", "grey", "brown"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/white-tan-smiley-colorblock-hoodie.jpeg"],
    thumbnail: "/products/white-tan-smiley-colorblock-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-white-smiley-colorblock",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-white-smiley-colorblock?aff=wbc",
    availability: true,
    rating: 4.4,
    popularity: 81,
    tags: ["hoodie", "colorblock", "smiley", "white", "tan", "streetwear"],
    style: ["streetwear", "casual"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-teal-mustard-colorblock",
    externalId: "wbc-hoodie-teal-mustard-colorblock",
    provider: "mock",
    brand: "Northpeak",
    name: "Teal Mustard Black Colorblock Hoodie",
    slug: "teal-mustard-black-colorblock-hoodie-wbc-hoodie-teal-mustard-colorblock",
    description: "Bold teal, mustard yellow and black triple colorblock hoodie with kangaroo pocket. High-street look.",
    category: "Hoodies",
    gender: "men",
    price: 1899,
    currency: "INR",
    originalPrice: 2499,
    discount: 24,
    colors: ["green", "yellow", "black"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/teal-mustard-black-colorblock-hoodie.jpeg"],
    thumbnail: "/products/teal-mustard-black-colorblock-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-teal-mustard-colorblock",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-teal-mustard-colorblock?aff=wbc",
    availability: true,
    rating: 4.5,
    popularity: 85,
    tags: ["hoodie", "colorblock", "teal", "mustard", "black", "streetwear"],
    style: ["streetwear", "casual"],
    occasion: ["college", "casual"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-hoodie-black-purple-plush",
    externalId: "wbc-hoodie-black-purple-plush",
    provider: "mock",
    brand: "Mono & Co",
    name: "Black Purple Gradient Plush Furry Hoodie",
    slug: "black-purple-gradient-plush-furry-hoodie-wbc-hoodie-black-purple-plush",
    description: "Plush furry black-to-purple gradient hoodie with kangaroo pocket. Bold soft streetwear statement.",
    category: "Hoodies",
    gender: "unisex",
    price: 2599,
    currency: "INR",
    originalPrice: 3299,
    discount: 21,
    colors: ["black", "purple"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/black-purple-gradient-plush-hoodie.jpeg"],
    thumbnail: "/products/black-purple-gradient-plush-hoodie.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-hoodie-black-purple-plush",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-hoodie-black-purple-plush?aff=wbc",
    availability: true,
    rating: 4.7,
    popularity: 93,
    tags: ["hoodie", "gradient", "purple", "black", "plush", "furry", "streetwear"],
    style: ["streetwear", "casual"],
    occasion: ["casual", "party"],
    season: ["winter"],
  }),
  localProduct({
    id: "wbc-tee-cream-rose-hooded",
    externalId: "wbc-tee-cream-rose-hooded",
    provider: "mock",
    brand: "Nordelle",
    name: "Cream Rose Pocket Tribal Trim Hooded Tee",
    slug: "cream-rose-pocket-tribal-trim-hooded-tee-wbc-tee-cream-rose-hooded",
    description: "Cream short-sleeve hooded tee with rose chest pocket and tribal trim on hood, sleeves and hem.",
    category: "T-Shirts",
    gender: "women",
    price: 1099,
    currency: "INR",
    originalPrice: 1499,
    discount: 27,
    colors: ["beige", "white", "multicolor"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/cream-rose-tribal-hooded-tee.jpeg"],
    thumbnail: "/products/cream-rose-tribal-hooded-tee.jpeg",
    productUrl: "https://example-retailer.com/p/wbc-tee-cream-rose-hooded",
    retailerName: "Demo Retailer",
    affiliateUrl: "https://example-retailer.com/p/wbc-tee-cream-rose-hooded?aff=wbc",
    availability: true,
    rating: 4.4,
    popularity: 80,
    tags: ["tshirt", "hooded", "rose", "tribal", "cream", "summer"],
    style: ["casual", "boho"],
    occasion: ["college", "casual", "vacation"],
    season: ["all"],
  }),
];

export function normalizeProviderProduct(raw: Record<string, unknown>): Product {
  const id = String(raw.id ?? raw.externalId ?? Math.random().toString(36).slice(2));
  const name = String(raw.name ?? raw.title ?? "Untitled product");
  const price = Number(raw.price ?? 0);
  const orig = raw.originalPrice != null ? Number(raw.originalPrice) : undefined;
  return {
    id, externalId: String(raw.externalId ?? id),
    provider: String(raw.provider ?? "external"),
    brand: String(raw.brand ?? "Unknown"),
    name, slug: slugify(name) + "-" + id,
    description: String(raw.description ?? ""),
    category: String(raw.category ?? "Accessories"),
    gender: (["men", "women", "unisex"] as string[]).includes(String(raw.gender)) ? (raw.gender as Product["gender"]) : "unisex",
    price: Number.isFinite(price) ? price : 0, currency: String(raw.currency ?? "INR"),
    originalPrice: orig, discount: orig ? Math.round(((orig - price) / orig) * 100) : 0,
    colors: Array.isArray(raw.colors) ? (raw.colors as string[]) : ["multicolor"],
    sizes: Array.isArray(raw.sizes) ? (raw.sizes as string[]) : ["M"],
    images: Array.isArray(raw.images) ? (raw.images as string[]) : [],
    thumbnail: String((Array.isArray(raw.images) ? raw.images[0] : raw.thumbnail) ?? ""),
    productUrl: String(raw.productUrl ?? "#"),
    retailerName: String(raw.retailerName ?? "Retailer"),
    affiliateUrl: raw.affiliateUrl ? String(raw.affiliateUrl) : undefined,
    availability: raw.availability !== false,
    rating: Number(raw.rating ?? 4), popularity: Number(raw.popularity ?? 50),
    tags: Array.isArray(raw.tags) ? (raw.tags as string[]) : [],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString()
  };
}

export function dedupeProducts(products: Product[]): Product[] {
  const seen = new Map<string, Product>();
  for (const p of products) {
    const key = `${p.provider}:${p.externalId}`.toLowerCase();
    if (!seen.has(key)) seen.set(key, p);
  }
  return Array.from(seen.values());
}

export class MockProductProvider implements ProductProvider {
  name = "mock";
  async searchProducts(query: string, filters?: ProductFilters): Promise<Product[]> {
    let list = [...MOCK_PRODUCTS];
    const q = (query || filters?.query || "").toLowerCase().trim();
    if (q) {
      list = list.filter((p) =>
        [p.name, p.brand, p.category, p.description, p.colors.join(" "), p.tags.join(" ")]
          .join(" ").toLowerCase().includes(q) ||
        q.split(/\s+/).some((t) => [p.name, p.brand, p.category, p.description, p.tags.join(" ")].join(" ").toLowerCase().includes(t))
      );
    }
    if (filters?.category) list = list.filter((p) => p.category.toLowerCase() === filters.category!.toLowerCase());
    if (filters?.gender) list = list.filter((p) => p.gender === filters.gender || p.gender === "unisex");
    if (filters?.brand) list = list.filter((p) => p.brand.toLowerCase() === filters.brand!.toLowerCase());
    if (filters?.minPrice != null) list = list.filter((p) => p.price >= filters.minPrice!);
    if (filters?.maxPrice != null) list = list.filter((p) => p.price <= filters.maxPrice!);
    if (filters?.color) list = list.filter((p) => p.colors.map((c) => c.toLowerCase()).includes(filters.color!.toLowerCase()));
    if (filters?.size) list = list.filter((p) => p.sizes.includes(filters.size!));
    if (filters?.minRating != null) list = list.filter((p) => p.rating >= filters.minRating!);
    switch (filters?.sort) {
      case "price-asc": list.sort((a, b) => a.price - b.price); break;
      case "price-desc": list.sort((a, b) => b.price - a.price); break;
      case "rating": list.sort((a, b) => b.rating - a.rating); break;
      case "newest": list.sort((a, b) => b.popularity - a.popularity); break;
      default: list.sort((a, b) => b.popularity - a.popularity);
    }
    return dedupeProducts(list);
  }
  async getProduct(id: string): Promise<Product | null> {
    return MOCK_PRODUCTS.find((p) => p.id === id || p.slug === id) ?? null;
  }
  async getProductsByCategory(category: string): Promise<Product[]> {
    return this.searchProducts("", { category });
  }
}

export const providerRegistry: Record<string, ProductProvider> = {
  mock: new MockProductProvider()
};

export function getProvider(name?: string): ProductProvider {
  return providerRegistry[name ?? process.env.PRODUCT_PROVIDER ?? "mock"] ?? providerRegistry.mock;
}
